# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Legal Center"
email: COO@yoki.inc
description: "株式会社Yokiの法務・コンプライアンスに関わる情報公開を行っています。"
baseurl: "/jekyll-help-center-theme"
url: "https://legal.yoki.inc"
twitter_username: "Yoki_Inc"
github_username:  "Yoki-Inc"
color_theme:  "#00253A"
color_text:  "#fff"
language:  "ja"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# GitHub
encding: utf-8
github : [metadata]
repository: Yoki-Inc/legal

# Plugins
plugins_dir:
  - jekyll-admin
  - jekyll-github-metadata
